version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-secret}

  backend:
    build:
      context: back-end
      target: ${TARGET:-development}
    env_file:
      - .env
    volumes:
      - ${PWD:-./back-end}:/app
      - /app/node_modules
    ports:
      - ${BACKEND_PORT:-3000}:3000
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://default:${REDIS_PASSWORD:-secret}@redis:6379

  frontend:
    build:
      context: front-end
    ports:
      - ${FRONTEND_PORT:-80}:80
    volumes:
      - ${PWD:-./front-end}:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  redis_data: