version: '3.4'
services:
  app:
    build:
      context: my-ts-server
      target: ${TARGET:-development}
    env_file:
      - .env
    volumes:
      - ${PWD:-./}:/app
    ports:
      - ${PORT}:3000
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret}
